---
spring:
  config:
    activate:
      on-profile: h2
  batch:
    job:
      enabled: false    # disable auto-run, weâ€™ll launch manually
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false     # optional, to inspect tables in browser
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.batch.core.repository.support: DEBUG
---
spring:
  application:
    name: tryout-spring-boot-batch
  datasource:
    diver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:30432/batch_database?currentSchema=batch_schema}
    username: ${DB_USERNAME:batch_user}
    password: ${DB_PASSWORD:password}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:batch_schema}
        show_sql: ${SHOW_SQL:false}
        use_sql_comments: ${SHOW_SQL:false}
        format_sql: ${SHOW_SQL:false}
    open-in-view: false
  batch:
    job:
      enabled: ${BATCH_JOB_ENABLED:false}
    jdbc:
      initialize-schema: ${BATCH_JDBC_INITIALIZE_SCHEMA:always}  # always, never, embedded
  liquibase:
    enabled: true
    liquibase-schema: ${database.liquibase_schema:liquibase_schema}
    default-schema: ${database.default_schema:batch_schema}
logging:
  level:
    org.springframework.jdbc.core: ${LOG_LEVEL:INFO}
    org.springframework.batch.core.repository.support: ${LOG_LEVEL:INFO}
